- README.md
- libs/live-fns/_index.js
- libs/live-fns/chrome-web-store.js
- package-lock.json
- package.json
Regarding this https://github.com/amio/badgen-service/issues/2#issuecomment-404457713
WIP, I'm pushing this mainly for feedback at this point.
- I want to bump `chrome-webstore` to version `1.0.0` before (eventually) merging, otherwise you won't receive any bugfixes using `^0.0.x`, after all it's a scraper so things can brake from time to time
- probably I'll change some of the meta keys before releasing version `1.0.0`
- the star rating currently uses `Math.ceil`, but in Chrome Web Store stars are rounded to 0.5, meaning: 3.5-4.0 = ★★★★☆, 4.0-4.5 = ★★★★☆ should be 4 and a half star, >4.5 = ★★★★★, no idea if there is a half full star symbol
Let me know what do you think!
> Add chrome-web-store badge

- libs/live-fns/chrome-web-store.js
- now.json
Two changes
- Add a 'v' to status text, make it clear a version number.
- Use 'orange' as status background for version under 1.0.
@simov What do you think?
> Update chrome-web-store version badge

- libs/index.md
- libs/live-fns/_index.js
- libs/live-fns/travis.js
- libs/redirect-fns/_index.js
- libs/redirect-fns/travis-org.js
- libs/redirect-fns/travis.js
- now.json
@styfle I have an idea to fill the gap between travis-ci.com & travis-ci.org (#4), request both and choose the right one:
https://github.com/amio/badgen-service/blob/47ae7df3fefefd4c8e03fa7b74609a837b433714/libs/live-fns/travis.js#L4-L17
> Update travis badge, compat with .com & .org

- libs/live-fns/npm.js
resolves #13 
Huh. That was fast and fun! :tada:
That's a service, that's a library, hooorey!
Shields sucks, for years. I started such service with koa back in 2014 if i remember correctly. But never got the time to finish it "officially" and release it.
It was times that there was mostly ES5 and no Babel or such :D 
It was times, that Shields "server.js" was around 2000-3000 lines of code... 
and HELL they still add to that file?! Currently it is 7900+, wtf.
> fix: add npm downloads total

- package.json
A lot better.
For devs like me that only have ESLint in their editor (VSCode), it's just enough.
Also, worth nothing, because both NPM and Yarn already support "flat deps".
> fix: add eslintConfig field, so IDEs are happy

- libs/live-fns/travis.js
Why? Because while doing #19 i've just realized that for some reason failing builds are shown as `unknown`. That so, becuase it response contains `failing` not `failed`.
I'm not sure if it depends on the different API endpoints, so.. for more safety lelts just make it regex.
> fix(travis): more ensurance

- libs/index.md
This changes the icons at the top to respect the style that the text says.
-------
> Fix classic vs flat choices

- libs/index.md
- libs/serve-index.js
That [index.md](https://github.com/amio/badgen-service/blob/dca83facc83927e7ad6f4cd7678d6db53562bab6/libs/index.md) is horrible for editing 🙀
This PR create a new index page:
- Use `lit-html` to generate examples section.
- Move "Available query params" to first screen.
- Add "Available icons" section.
Preview at https://badgen-new-index.now.sh
> New index page

- libs/serve-badge.js
This allows things like this:
to look like this:
If this is something you’re willing to support. :)
> Allow specifying an empty label

- libs/icons/patreon.svg
- libs/index.md
- package-lock.json
Why one is better? I'm still wondering which one to use in my READMEs..
> fix: add patreon badge, show static usage

- libs/serve-index.js
The footer link for Now Cloud was empty
> Fix empty link

- libs/index.md
- libs/serve-index.js
I've added links to the documentation in the examples page
Don't hesitate to tell me if you would have designed them differently
> Add documentation links

- libs/docs/uptime-robot.md
- libs/index.md
As discussed in issue #70, uptime-robot needs  a little documentation about where to find the API key
> Add uptime-robot documentation

- libs/live-fns/packagist.js
- libs/utils/compare-versions.js
- package-lock.json
- package.json
The packagist version detection for `latest` ist currently broken when a package published a patch version for a older minor release. Than this patch version is detected as the latest release (e.g.`v1.0.0` => `v2.0.0` => `v1.0.1`).
This PR adds a `compareVersions` sort function based on [compare-versions](https://github.com/omichelsen/compare-versions) to sort the versions returned from the packagist API before detecting the latest.
Other changes:
- `nodev` filters out every version containing `dev` (e.g. `1.0.x-dev`)
- `pre` filters out versions starting with `dev` (e.g. `dev-master`)
- Some minor code improvements
> fix(live-fns/packagist): version detection

- libs/index.md
- libs/live-fns/packagist.js
This pull request add support for Packagist license. Not sure if you want to go with `license` or `l`. I've chosen `license` to be consistent with npm and pypi.
> Add packagist license badge

- .codeclimate.yml
- libs/index.md
- libs/live-fetcher.js
- libs/live-fns/github.js
- Replace `axios` with `got`
- Separate assets downloads count, usage `/dt/` => `/assets-dl/`
- Split `stats()` into resoStats, makeRepoQuery, repoQueryBodies
Make codeclimate happy.
> live-fns: (github) refactor & use `got`

- libs/serve-docs.js
- libs/serve-index.js
- now.json
Right now, badgen is using a fixed Google Analytics tracking ID.
This ID is used by forks of badgen, as well as local versions running on a dev server, which tend to alter real statistics from `badgen.net`.
This ID should be used only in production, and maybe you'd like to change it later without editing your code.
Maybe you can add your tracking ID as a secret : 
```sh
now secrets add tracking-ga "UA-4646421-14"
```
> Retrieve trackingGA from env

- libs/live-fns/david.js
This PR fixes the [only alert produced by LGTM](https://lgtm.com/projects/g/amio/badgen-service/alerts/?mode=list).
The problem is a little subtle, the truthyness of `path` will always be `true` because the truthyness of an empty array is `true` (`!![] == true` even though `[] == false`): https://www.nfriedly.com/techblog/2009/07/advanced-javascript-operators-and-truthy-falsy/
So a path will always be added to the query, even if no path arguments were given, resulting in `?path=` being added to the end. This corrects the condition so that no path is added to the query if it's empty.
> fix useless conditional in david.js

- libs/index.md
- libs/serve-metadata.js
- service.js
After opening #128, but before seeing #99, I was thinking that it would be a good idea to automatically populate the list of icons on the homepage, rather than having to maintain the list there, and remembering to add icons each time a new one is added.
After seeing that some are deliberately not on there, I think this still could be useful now i've added a blacklist, and will self-document the fact that some badges have deliberately been chosen not to be on there, and avoid any further confusion of users introducing PRs like #128 and #99.
> icons: automatically populate list in index.md

- libs/live-fns/lgtm.js
Our API has been updated now, and `application/json` `Accept` headers work, so this special behaviour is no longer needed. :smile:
> live-fns: (lgtm) use default accept header

- README.md
Now that the lgtm service is added, the logo has a custom width, and badgen-service's alerts are down to 0, time to add badges to the README? :-D
Also, @amio would you like to enable the pull request integration here to help prevent new alerts appearing? https://lgtm.com/projects/g/amio/badgen-service/ci/
> docs: add lgtm badge

- libs/index.md
- libs/serve-badge.js
I'd love to be able to override a live badge color, for example having my npm download count in pink, or my license badge in some weird color I like.
This PR adds an optional 'color' option to the badge handler (live & static), which supports color names and hex strings.
E.g:  
- ![Badge](https://badgen-service-artxnvyutq.now.sh/npm/dm/express?color=pink)  `/npm/dm/express?color=pink`
- ![Badge](https://badgen-service-artxnvyutq.now.sh/npm/license/lodash?color=9ea7f9
)  `/npm/license/lodash?color=9ea7f9`
> Override badge color

- libs/live-fns/david.js
I like to add the `/david/dev` and `/david/dep` to all projects and it looks a little odd when they are not both green.
My subjective opinion is that zero dependencies should be considered "passing" (up to date) and should be green, not blue.
> Change david-dm to green w/zero deps

- libs/live-fns/github.js
When using the 'tag' option to get the latest tag - it gets the oldest (first) tag instead of the latest one.
This PR fixes this.
> github tag got the first instead of last

- libs/examples-live.js
- libs/index.md
The CodeClimate badges for Jekyll stopped working and I think using CodeClimate's own repo would assure that this badge will always work even in the advent where a repo (like Jekyll) could stop using CodeClimate.
> Replaced Jekyll repository for CodeClimate's own repo

- endpoints/dependabot.ts
- libs/badge-list.ts
Based on this conversation: https://github.com/dependabot/feedback/issues/6#issuecomment-503994253
Accepts a private repo id, for the example I filtered out `<repo_id>` since I don't have an actual private repo to add (and I don't think it is a good idea), and used greenkeeper because it is a repo I can't see ever implementing dependabot, so it shows both states.
fixes: #283
> Add dependabot endpoint

- libs/badgen-serve.ts
`.catch` [here](https://github.com/badgen/badgen.net/blob/master/libs/badgen-serve.ts#L61) only exists when a icon query exists, resolving the iconPromise to default allows it to catch regardless.
fixes: #290
> Resolve iconPromise to undefined by default

- endpoints/github.ts
Maybe we might need to widen a bit the page width. Cuz I think those examples are needed so user can see what and how. I also renamed few examples, because they are not exactly `ci job` or `ci status`, it's a github status, more precisely context status.
So now don't even need separate live badges for those :D 
Because:
_combined appveyor with custom label and icon_
```
https://badgen.net/github/status/zeit/hyper/efeedd0a9d3/continuous-integration/appveyor?label=windows&icon=appveyor
```
_combined travis with custom label and icon_
```
https://badgen.net/github/status/zeit/hyper/efeedd0a9d3/continuous-integration/travis?label=travis&icon=travis
```
_combined circleci with custom label and icon_
```
https://badgen.net/github/status/zeit/hyper/efeedd0a9d3/ci:circleci?label=circleci&icon=circ …
```
> Combined context status

- static/index.css
It appears due to `100vw` but since there is a vertical scrollbar it has only `100vw - scrollbar width` of width.
> Removes the useless horizontal scrollbar.

- components/home-intro.js
The example for the `label` parameter is currently the same as for `icon` (probably a copy&paste whoopsie). This PR makes it an actual example for `label` overriding.
> Fix example for `label` override

- libs/badgen-serve.ts
Using `yarn dev` was not possible due to an error that was thrown while trying to assign the `icon` property to the `query` variable which only allows properties specified in `ParsedUrlQuery`.
```
72:9 Type 'string | undefined' is not assignable to type 'string | string[]'.
Type 'undefined' is not assignable to type 'string | string[]'.
70 |         params.status = simpleDecode(params.status)
71 |
> 72 |         query.icon = icon === '' ? params.subject : icon
|         ^
73 |
74 |         if (query.style === undefined) {
75 |           const host = req.headers['x-forwarded-host'] || req.headers.host
> Build error occurred
```
> fix: ignore ParsedUrlQuery modification for serve

- endpoints/github.ts
fixes #304 & fixes #310
```
/github/checks/:owner/:repo/:ref?
/github/checks/tunnckoCore/opensource?label=build&icon=github
```
https://badgennet.charlike-oss.now.sh/github/checks/tunnckoCore/opensource
[![](https://badgennet.charlike-oss.now.sh/github/checks/tunnckoCore/opensource)](https://github.com/tunnckoCore/opensource/actions)
[![](https://badgennet.charlike-oss.now.sh/github/checks/tunnckoCore/opensource?label=build&icon=github)](https://github.com/tunnckoCore/opensource/actions)
The example is pointing to my monorepo. If there are better examples, okay.
I'm planning to use GHA non-stop anyway. Also, the repo is not some dumb one, but my main focus and moving everything there.
> feat: support Checks API, and so GitHub Actions badge

- api/badgesize.ts
Double slashes are redirected to a single slash so one solution here is to omit the double slash.
> Fix badgesize url

- now.json
It doesn't look like there is any central database dependency so you could run badgen in all regions.
See comment from @XhmikosR here https://github.com/styfle/packagephobia/pull/470#issuecomment-558744451
> chore: update now.json to use all regions

- api/docker.ts
Shows the size for a Docker image.
Defaults to the latest tag and amd64 architecture as they are most popular but a  custom tag or arch can optionally be specified with `/docker/size/:scope/:name/:tag?/:architecture?`.
Notes:
- `/docker/size/library/ubuntu` is a little slow, I've re-used the ubuntu image as that's what's in the other library examples. The reason it's slow is it has to paginate through a lot of API responses to find the tag as there are a huge amount of tags on Docker Hub for Ubuntu.
- I'm manually calculating the size instead of using `millify` because `millify` calculates MB when what we actually want is MiB to be consistent with the Docker Hub UI.
> Add Docker image size support

- api/travis.ts
use red for `failed` and `failing` instead of orange.
> fix: travis badge color (#328)

- api/npm.ts
no matter the dist-tag it should follow the versionColor
> badge(npm): always follow versionColor

- .dockerignore
This prevents cache busting while building the Docker Image when only some git data changes like doing a fetching or rebasing without actual changes.
> Add .git to .dockerignore

- api/haxelib.ts
- libs/badge-list.ts
- package-lock.json
- package.json
Fetch library information from https://lib.haxe.org using [`haxe-rpc-client`](https://npm.im/haxe-rpc-client).
```
/haxelib/:topic/:project
```
- `d` (downloads)
- `dl` (downloads latest version)
- `license`
> Add haxelib service

- api/homebrew.ts
Homebrew supports API data access for both formulas and casks:
- for formulas
`https://formulae.brew.sh/api/formula/<name>.json`
- for casks
`https://formulae.brew.sh/api/cask/<name>.json`
This PR adds support for displaying cask versions and download analytics for formulas.
This adds new `/homebrew` route subroutes:
- for download analytics (monthly & yearly downloads)
```
/homebrew/dm/:pkg
/homebrew/dy/:pkg
```
- for displaying cask version
```
/homebrew/cask/v/:pkg
```
---
> Homebrew: add cask version & download analytics support

- api/opam.ts
- libs/badge-list.ts
Scrape package information from https://opam.ocaml.org using `cheerio`.
```
/opam/:topic/:pkg
```
- `dm` (monthly downloads)
- `license`
> badge: add opam service

- api/scoop.ts
- libs/badge-list.ts
[Scoop](https://github.com/lukesampson/scoop) is a command-line package installer for Windows.
The app information is fetched from either [main](https://github.com/ScoopInstaller/Main/tree/master/bucket) or [extras](https://github.com/lukesampson/scoop-extras/tree/master/bucket) bucket hosting json manifests.
This adds two new handlers:
```
/scoop/:topic<v|license>/:app
/scoop/:bucket<main|extras>/:topic<v|license>/:app
```
- `license`
> Add Scoop badge

- api/homebrew.ts
Extract Homebrew api url to constant and use it as `prefixUrl` when creating custom `got` instance.
> Homebrew: use preconfigured `got` client

- api/pub.ts
- libs/badge-list.ts
Fetch package information from https://pub.dev using combination of API access and `cheerio` powered scraping.
This adds two new handlers:
```
/pub/:topic<v|sdk-version>/:pkg
/pub/:topic<likes|dart-platform|flutter-platform|license>/:pkg
```
- `sdk-version` (version range of supported Dart SDKs)
- `likes` (package likes count from https://pub.dev)
- `dart-platform` (union of supported platforms)
- `flutter-platforms` (union of supported flutter platforms)
- `license`
This closes #385 
@cedx If you have any more ideas or suggestions please share them. Your feedback is more than welcome! 😉
> Add pub badge (Dart)

- api/tidelift.ts
- libs/badge-list.ts
Reads Tidelift subscription status from their badge. (As explained here: https://github.com/badgen/badgen.net/issues/359#issue-570948860)
```
/tidelift/:platform/:name
```
> Add Tidelift subscription badge

- api/f-droid.ts
- libs/badge-list.ts
- package-lock.json
- package.json
Reads app metadata from https://gitlab.com/fdroid/fdroiddata
```
/f-droid/:topic<v|license>/:appId
```
- `license`
> Add F-Droid support

- api/github.ts
- api/winget.ts
- libs/badge-list.ts
- libs/github.ts
[winget](https://github.com/lukesampson/scoop) is a command-line package installer for Windows. (See announcement post: https://devblogs.microsoft.com/commandline/windows-package-manager-preview/)
The app information is fetched from [community repo](https://github.com/microsoft/winget-pkgs) hosting YAML manifests and parsed using [`yaml`](https://npm.im/yaml) package.
This adds new handler:
```
/winget/:topic<v|license>/:appId
```
- `license`
> Add winget support

- api/mastodon.ts
- libs/badge-list.ts
Fetch followers for a given user from the default (mastodon.social) or custom Mastodon/Pleroma instance.
```
/mastodon/follow/:userId/:instance?
```
As proposed here: https://github.com/badgen/badgen.net/issues/362#issuecomment-615880134
> Add Mastodon/Pleroma support

- api/snyk.ts
- libs/badge-list.ts
- libs/create-badgen-handler.ts
Vulnerability scan results are parsed from official Snyk's badge using `cheerio`.
```
/snyk/:user/:repo/:branch?
```
Additionally `targetFile` query param can be passed to the handler.
This closes #340
> Add Snyk support

- api/deepscan.ts
- libs/badge-list.ts
This PR adds support for [DeepScan](https://deepscan.io). (Closes #307)
```
/deepscan/:topic<grade|issues|lines>/team/:teamId/project/:projectId/branch/:branchId
```
> Add DeepScan.io support

- README.md
- api/npm.ts
- libs/github.ts
- Allow specifying of custom endpoints for NPM and Github. This is to allow usage in a self-hosted enterprise environment.
- Support querying NPM for all package info (scoped + non latest tags). Support abbreviated metadata queries for a bit better performance.
- Support to disable use of unpkg for package lookups (for selfhosted/private NPM use) when `NPM_REGISTRY` is defined.
- Added info on all supported environment variables.
Note:
My custom registry does not support abbreviated NPM metadata unfortunately, so some large internal packages can still time-out. Trying to think of a solution for this.
Maybe either configurable request timeout? Or perhaps an internal node cache (even if it is somewhat short, a minute or two) to avoid undue load on the registry? -- Or both. Open to …
> feat: allow customn npm and github endpoints

- api/github.ts
There's a status "cancelled" in github checks we missed.
- before https://badgen.net/github/checks/vercel/vercel/6c81a873384f62ecfc49639d344f3f0aeb3dd558
- after https://badgennet-665t3sr35.vercel.app/github/checks/vercel/vercel/6c81a873384f62ecfc49639d344f3f0aeb3dd558
cc @tunnckoCore @styfle
> fix(github): status might be "cancelled"

- api/gitlab.ts
- libs/badge-list.ts
- libs/gitlab.ts
- now.json
fixes #297 
I've added the following badges for Gitlab.
I've covered some of them, but their API and documentation beat me many times 😆  (especially since I am not familiar with GraphQL or complex Gitlab project flows with lots of Jobs, tags and other things). Any suggestion and/or request for changing something is welcome 😄 
❗ When deploying the next time with this fix (if merged, of course) there is needed to add a new env variable named `GITLAB_TOKENS`(can be a list, same as GITHUB_TOKENS).  It should have `read_api` scope
> PR for adding some badges for Gitlab

- api/github.ts
Since there is no API to get dependabot status, for now check if file `.github/dependabot.yml` exists.
fixes: #419
> badge(github): add dependabot support

- api/bundlephobia.ts
Hi! Love your project and use it quite often.
My hobby is creating tiny libraries and I know many people who need badges to promote that their JS-libraries have no dependencies (or have few of them). Also tagging a project as side-effect-free/tree-shakable would be very helpful for developers.
Example: https://github.com/pastelsky/bundlephobia/issues/224
So I decided to create a small PR to add these badges.
They get data from the bundlephobia's API that you already use, so it's actually not a big deal.
> Bundlephobia: dependency-count and tree-shaking badges

- api/chrome-web-store.ts
version number bumped according to the check https://github.com/badgen/badgen.net/runs/1219336506?check_suite_focus=true
> fix(chrome-web-store): bump api version (fix #431)

- libs/badge-list.ts
Now the recommended way is [GitHub badge](https://badgen.net/github/#github-dependabot-owner-repo)
> chore: remove dependabot from badge list

- api/docker.ts
- libs/docker.ts
This PR facilitates generating architecture variant layer badges such as `arm/v6` VS `arm/v7` VS `arm64/v8`. It fulfills the layer feature requests in issue [#185](https://github.com/badgen/badgen.net/issues/185). Unfortunately, the DockerHub Registry API Scheme v2 does not support `blob` layers, and instead shows `fsLayers` which do not include layers of size 0 (ie: `CMD`, `ENV`, `LABEL`, `ENTRYPOINT`, etc...). For this reason, users will notice a difference in the number of layers between microbadger and badgen.net.
This can be tested using the multi-architecture [lucashalbert/curl:latest](https://hub.docker.com/r/lucashalbert/curl)  dockerhub image like so:
* [https://badgen.net/docker/layers/lucashalbert/curl/latest/arm/v6](https://badgen.net/docker/layers/lucashalbert/curl/latest/arm/ …
> feat(docker): Add image layers handler

- .github/workflows/nodejs.yml
> chore: no need to run lint on pull requests

- api/ctan.ts
- libs/badge-list.ts
```
/ctan/:topic/:pkg
```
- `license`
> Add CTAN service

- api/cpan.ts
- libs/badge-list.ts
```
/cpan/:topic/:distribution
```
- `license`
- `size` (distribution size)
> Add CPAN service

- .github/workflows/nodejs.yml
- api/ctan.ts
The lint job didn't run on pull requests. Changed the trigger to simply on all pull requests.
> ci: run lint job on all pull requests

- api/mastodon.ts
Swap defunct https://pleroma.site with https://anime.website.
> Fix Pleroma badge

- api/melpa.ts
- libs/badge-list.ts
> Add MELPA service

- api/wapm.ts
- libs/badge-list.ts
This adds new handler/s powered by WAPM (WebAssembly Package Manager) registry - https://wapm.io :
```
/wapm/:topic<v|license|size|abi>/:namespace/:pkg
/wapm/:topic<v|license|size|abi>/:pkg
```
- `license`
- `size` distribution size
- `abi` webassembly ABI (WASI/emscripten)
> Add wapm service

- api/shards.ts
- libs/badge-list.ts
This adds a new handler powered by scraping https://shardbox.org:
```
/shards/:topic<v|license|crystal|dependents>/:shard
```
- `license`
- `crystal` (Crystal version)
- `dependents` (number of dependents)
> Add Crystal shards service

- vercel.json
> "@now/node" is deprecated and will stop receiving updates on December 31, 2020. Please use "@vercel/node" instead.
- https://www.npmjs.com/package/@now/node
- https://vercel.com/blog/zeit-is-now-vercel
> Change `@now/node` to `@vercel/node`

- api/github.ts
Error log:
```
[GET] /github/checks/contributte/translation
11:04:25:55
2021-01-08T03:04:26.124Z	6abb7984-f2b1-47d6-8c2d-0733ea638f96	ERROR	UCE /github/checks/contributte/translation Unknown states: success,success,success,success,success,success,success,skipped,success,success,success,success,success,success,success,success,skipped,success,success,success,success,success,success,success,success,success,success Error: Unknown states: success,success,success,success,success,success,success,skipped,success,success,success,success,success,success,success,success,skipped,success,success,success,success,success,success,success,success,success,success
at combined (/vercel/workpath1/api/github.ts:105:9)
at Object.checks (/vercel/workpath1/api/github.ts:121:13)
at processTicksAndRejections …
```
> fix: handle "skipped" status in github combined checks (#471)

- api/runkit.ts
Swap https://runkit.com/amio/satisfaction endpoint with newly created https://runkit.com/vladimyr/metaweather (returns weather info from https://www.metaweather.com).
Refactor RunKit badge handler to support both:
1. legacy `/runkit/:endpoint-id/:path*` URL patterns
2. new `/runkit/:owner/:notebook/:path*` URL patterns
Update documentation & examples to use new `/runkit/:owner/:notebook/:path*` URLs. :tada:
> Fix RunKit badges

- api/peertube.ts
- libs/badge-list.ts
This adds new handler/s powered by [PeerTube REST API](https://docs.joinpeertube.org/api-rest-reference.html):
```
/peertube/:instance/:topic<comments|views>/:video-uuid
/peertube/:instance/:topic<votes>/:video-uuid/:format?<likes|dislikes>
/peertube/:instance/:topic<followers>/:account/:channel?
```
---
While it doesn't address #219 directly it is definitely a step in the proposed direction :rocket:
> Add PeerTube service

- api/elm-package.ts
- libs/badge-list.ts
This adds new handler powered by [Elm Package registry](https://package.elm-lang.org):
```
/elm-package/:topic<v|version|license|elm>/:owner/:name
```
- `v`/`version` (version)
- `license`
- `elm` (Elm version)
> Add Elm package service

- api/elm-package.ts
Change version badge label from `version` to `elm package`:
> Fix Elm Package service

- api/cran.ts
- libs/badge-list.ts
This adds new handler/s powered by [METACRAN API](https://www.r-pkg.org/services#api) & [cranlogs.app](https://cranlogs.r-pkg.org/#jsonapi/):
```
/cran/:topic<v|version|license|r|dependents>/:pkg
/cran/:topic<dd|dw|dm|dt>/:pkg
```
- `v`/`version` (version)
- `license`
- `r` (R version)
- `dependents`
- `dd` (daily downloads)
- `dw` (weekly downloads)
- `dm` (monthly downloads)
- `dt` (total downloads)
> Implement CRAN service

- api/dub.ts
- libs/badge-list.ts
This adds new handler powered by [DUB (dlang package) registry](https://code.dlang.org):
```
/dub/:topic<v|version|license|dd|dw|dm|dt|rating|stars>/:pkg
```
- `v`/`version` (version)
- `license`
- `dd` (daily downloads)
- `dw` (weekly downloads)
- `dm` (monthly downloads)
- `dt` (total downloads)
- `rating`
- `stars`
> Add `dub` service (dlang package manager)

- api/devrant.ts
- libs/badge-list.ts
This adds new handler/s powered by [devRant](https://devrant.com) API:
```
/devrant/score/:user-id
/devrant/score/:username
```
---
Inspired by #219 :grin:
> Add devRant score badge

- api/maven.ts
This alters `/maven/v/maven-central/:group/:artifact` handler to:
```
/maven/v/:repo<maven-central|jcenter>/:group/:artifact
```
Additionally, it incorporates the following changes:
- refactoring Maven metadata param processing
- swapping `cheerio` with regexes
---
Closes #480
> Add JCenter support to Maven service

- api/github.ts
Order tags by creation before retrieval, fixes #484 :bug:
> Fix last tag retrieval from GitHub

- api/cpan.ts
Use API to get likes & runtime version - no more HTML scraping :tada: 
New _dependents_ badge :tada: 
---
> Fix Perl release & runtime version

- api/github.ts
- api/npm.ts
This is a continuation of #406 with `cheerio` being replaced by regexes :tada: 
---
> Millify Github & npm dependents count

- api/mastodon.ts
Pleroma supports account lookup using `username` and for Mastodon, it is possible to extract user id from users' feed. :tada: 
---
> Generate Mastodon/Pleroma badge using `username@instance` handle

- api/gitter.ts
- api/matrix.ts
- libs/badge-list.ts
This PR adds support for Gitter and Matrix badges. Former is powered by scraping public Gitter rooms while latter uses Matrix client API to obtain public room information. :tada: 
In response to https://github.com/badgen/badgen.net/issues/362#issuecomment-601659346
> Looks like two more live badges to go, discourse and matrix.
One down, one more to go :wink:
> Introduce Gitter and Matrix member count badges

- api/open-vsx.ts
- libs/badge-list.ts
Open VSX is an alternative to the Visual Studio Code Marketplace, operated by the Eclipse Foundation
> Add support for Open VSX

- api/discord.ts
- libs/badge-list.ts
This PR adds support for the Discord badge powered by [Discord API](https://github.com/badgen/badgen.net/issues/362#issuecomment-601679924).
In response to https://github.com/badgen/badgen.net/issues/362#issuecomment-601679924
> Introduce Discord (online) members badge

- api/snapcraft.ts
- libs/badge-list.ts
This adds new handlers powered by [Snapstore Devices API](https://api.snapcraft.io/docs/):
```
/snapcraft/:topic<v|version|size>/:snap/:architecture?/:channel?
/snapcraft/:topic<l|license|arch|architecture>/:snap
```
---
Shields.io badge request: https://github.com/badges/shields/issues/2544
Snapstore badge proposal: https://github.com/snapcore/snap-store-badges/issues/14
> Add snapcraft.io service

- api/open-vsx.ts
I somehow missed the ratings option in the Open VSX API. But now that there are two topics with the letter `r`, I'm having second thoughts about the abbreviated forms. Any opinions on whether I should remove that or do you fear a breaking change like this?
I'm wondering why there's no recommendation or at least a standardized way for some of these (e.g. I've seen `d` and `dl` as short forms for `downloads`). Personally, when in doubt, I'd opt for the full name topics.
> Add support for Open VSX ratings

- api/https.ts
Removes unnecessary `then` from the second step of the "Use Badgen with HTTPS Endpoint" example
> docs: remove repeated word in https documentation

- api/pypi.ts
This extends the existing PyPI service with a new handler for generating badge listing supported Python versions:
```
/pypi/python/:project
```
---
This is based on @NickKaramoff's work made in #513 Due to lack of activity there, I decided to take my patch and convert it into another PR which closes #513.
> Add Python version support to PyPI service

- api/npm.ts
Seems npm removed `license` field from their package meta api.
> fix(npm): license field removed from meta api (fix #436)

- api/github.ts
This makes combined checks and combined statuses use the default branch when the branch is omitted.
It is inspired by the below comment.
> It would be nice to auto detect default branch.
> 
> For now it is just for "master" branch, thanks @lens0021 !
_Originally posted by @amio in https://github.com/badgen/badgen.net/issues/523#issuecomment-826226596_
I did not test this and it will be a breaking change, however.
> badge(github): Use default branch for checks and status

- api/nuget.ts
Add support for total downloads to the existing NuGet badge. NuGet package IDs are treated as all lowercase in the API, so I've added lowercase conversion to the existing badge.
```
/nuget/dt/:project
```
> Add total downloads support to NuGet

- api/github.ts
Hi! Thank you for a cool service 😆
I found that when I try to make some of my badges for GitHub checks, I get 500 errors.
e.g. <https://badgen.net/github/checks/blooper05/action-rails_best_practices>
I have investigated and found that the checks in those errored repositories contain the `neutral` on `conclusion` property.
I also read the documents accordingly and found that there are other `conclusion`s that are not covered by the current implementation.
ref. <https://docs.github.com/en/rest/checks/runs#list-check-runs-for-a-git-reference>
So, I have fixed these issues 👍 
Please check my changes and merge them if you like them. Thanks!
> fix(github): Cover all conclusion enums in the GitHub check-runs API

- api/npm.ts
Types can also be specified in the `exports` property of `package.json` files.
Since this property supports [multiple levels of nesting](https://nodejs.org/api/packages.html#nested-conditions), my proposal recursively scans them all.
> fix(api/npm): scan `exports` for types

- api/pub.ts
The response from pub.dev's `api/packages/${pck}/metrics` API has changed.
`derivedTags` is now available from `$.scorecard.panaReport.derivedTags`
> Fix issue when loading platform/sdk info from pub.dev

- api/gitlab.ts
Leading slashes in `input` are disallowed  when using `prefixUrl` option. [Reference1](https://github.com/sindresorhus/got/blob/4d12bbd7e18866739254ac0f256b850a3d58dba6/source/core/options.ts#L1230) [Reference2](https://github.com/sindresorhus/got/blob/4cdcca382659050e1c73c7eb9542c8fb871d10aa/test/arguments.ts#L434-L439)
Fix #564
I have test it: [/gitlab/last-commit/gitlab-org/gitlab-development-kit](https://badgen-gitlab.vercel.app/gitlab/last-commit/gitlab-org/gitlab-development-kit) ![](https://badgen-gitlab.vercel.app/gitlab/last-commit/gitlab-org/gitlab-development-kit).
The badgens for `commits count` or `branches` are broken because gitlab api changed.
> fix(api/gitlab): remove leading slashes in restPaths

- vercel.json
`npm` badge and `chrome-web-store` badge is already migrated
> chore: update vercel proxy setup

- libs/badge-list.ts
- libs/badge-list2.ts
- next.config.js
- pages/api/hackage.ts
- vercel.json
The broken badge is caused by updated cabal file version (v2.x)
Fixed preview https://badgennet-git-migrate-hackage-badgen.vercel.app/hackage/v/BNFC
> feat: migrate /hackage badges, and fixes #585

- libs/create-badgen-handler-next.ts
- libs/fetch-icon.ts
External icon is back:
https://badgennet-git-external-icon-badgen.vercel.app/static/OpenAI/GPT-4?icon=https://simpleicons.vercel.app/openai/fff&label
> fix: support for external icon. fix #570

- components/builder-hints.tsx
"generater" should be "generator", see
https://www.merriam-webster.com/dictionary/generator
https://dictionary.cambridge.org/dictionary/english/generator
> Fix homepage typo

- libs/serve-doc-next.ts
- libs/serve-doc.ts
`serve-doc` and `serve-doc-next` footer differed from the main `footer.tsx` file in styling and anchor links.
Updated the CSS to match as best I could. They're not the exact same but they're close.
<details>
<summary>Screenshots</summary>
** Disregard the weird color of the heart emoji in `with ♥ by`, something isn't rendering right on my laptop, it renders fine on a phone.
`https://badgen.net/memo`
`http://localhost:3000/memo`
`Before: left` `After: right`
</details>
> fix: Update footer in serve doc

- components/footer.tsx
- libs/serve-doc-next.ts
- libs/serve-doc.ts
Image src coming from `simpleicons`  for `/twitter`  wasn't reendering a twitter icon in the `serve-doc` and `serve-doc-next` footer.
<details>
<summary>Screenshots</summary>
</details>
> fix: Change simpleicons twitter --> x to resolve icon render

- pages/api/pub.ts
[![pub-dm](https://github.com/user-attachments/assets/c70baa00-b8f2-48e1-b0b8-b7946fdcacff)](https://pub.dev/packages/riverpod/score)
(e.g. `https://badgen.net/pub/dm/riverpod`)
- Introduced a new endpoint for monthly downloads under '/pub/dm/:pkg'.
- Updated the apiHandler to handle the new 'dm' topic for fetching download counts.
> feat(pub): add monthly downloads endpoint
