badgen/badgen.net

- README.md
- libs/redirect-fns/_index.js
- libs/redirect-fns/travis-org.js
> Add redirect badge: travis-org #4

- libs/live-fns/chrome-web-store.js
Just noticed this same bug in one of my projects. It should remove all `,` not only the first one.
> Fix users count for chrome-web-store badge

- libs/live-fns/_index.js
- libs/live-fns/codecov.js
- package.json
resolves #12 
Sorry for adding `eslintConfig` field, but is for better editor integration... 
Worth nothing.
> feat: add support for codecov coverage

- libs/live-fns/_index.js
- libs/live-fns/github.js
- package.json
resolves #14, more can be added if some needs
> feat: start github live badges

- libs/live-fns/npm.js
> fix: updates for downloads per day

- libs/live-fns/npm.js
address #23 and https://github.com/amio/badgen-service/pull/17#issuecomment-406773354
> fix(npm): use /point instead of /range

- libs/index.md
- libs/live-fns/npm.js
- package-lock.json
fix: resolves #34 and resolves #35
> fix: npm badges and dist tags

- libs/live-fns/npm.js
@tusbar Thank you for providing such stable badge service.
Some tiny refactoring when reading the codes.
> refactor: remove duplicate assignment on pkg

- libs/index.md
- libs/live-fns/codecov.js
- libs/live-fns/coveralls.js
Add 1 decimal to both codecov and coveralls.
> Use codecov api for coverage

- libs/index-api.md
- libs/live-fetcher.js
- libs/live-handlers.js
- libs/serve-api.js
- libs/serve-cache.js
- now.json
- package.json
- service.js
Mainly two purposes:
1. Provide https://api.badgen.net
2. Serve this api behind Now CDN as a cache layer
> feat: add api server

- libs/index.md
- libs/live-fns/_index.js
- libs/live-fns/packagist.js
Adds support for https://packagist.org/ which is used for PHP
> Packagist support

- libs/index.md
- libs/live-fns/packagist.js
Adding more badges for packagist and changing some labels.
> feat: name, language & github badges for packagist

- libs/index.md
- libs/live-fns/_index.js
- libs/live-fns/rubygems.js
Adds support for https://rubygems.org/ which is used to publish ruby gems (packages)
> RubyGems Support

- libs/index.md
- libs/live-fns/github.js
- add GitHub "closed issues" and "license" badges
- document missing GitHub badges
- make `stats` function more dynamic
- some minor cleanup
> github: add "closed issues" and "license" badges

- libs/live-fns/apm.js
Whoops. Somehow overlooked this 😅
> fix version badge color

- libs/docs/packagephobia.md
- libs/docs/uptime-robot.md
The docs should show the website of the service
> Add website to docs

- libs/index.md
- libs/live-fns/_index.js
- libs/live-fns/lgtm.js
This PR introduced the LGTM service badges: (see #124)
> live-fns: (lgtm) introduce lgtm service

- libs/index.md
- libs/live-fns/_index.js
- libs/live-fns/xo.js
I like having xo badges on my repos. :D
/cc @sindresorhus
> Add xo badges

- libs/examples-live.js
- libs/index.md
- libs/live-fns/_index.js
- libs/live-fns/azure-pipelines.js
This is my first PR to this repo, so I'm not familiar too much...
> Add Azure Pipelines (close #200)

- libs/live-fns/circleci.js
> live-fns: simplify circleci badge - success/failed

- endpoints/codacy.ts
- libs/badge-list.ts
Codacy has no public API, so it has to parse SVG via regex;
> Add codacy badges (coverage, grade)

- endpoints/packagist.ts
Adds a new badge for http://packagist.org that shows the required PHP version if possible.
> feat: add PHP version badge for packagist

- package-lock.json
- package.json
Ran https://github.com/jeffijoe/typesync to install missing type packages.
> chore: install missing TypeScript typings

- package-lock.json
- package.json
Node.js 12 is supported, according to https://github.com/zeit/now/issues/3363#issuecomment-559200453 🎉
> chore: use nodejs 12

- api/github.ts
- package-lock.json
- package.json
- cleanup outdated example
- bump deps
> Cleanup github badge example

- .github/workflows/nodejs.yml
- api/azure-pipelines.ts
- api/badgesize.ts
- libs/serve-badge.ts
- set cdn cache to 5 mins
- fix lint errors
- add github action config with linter
> chore: limit CDN cache to 5 mins

- libs/create-badgen-handler.ts
- libs/measurement-protocol.ts
- package-lock.json
- package.json
No more `request` bundled with `universal-analytics`.
> chore: replace universal-analytics with measurement-protocol.ts

- .github/workflows/deploy.yml
- .github/workflows/nodejs.yml
Due to a cache issue, https://flat.badgen.net need to be deployed separately.
> chore: deploy to flat.badgen.net with GitHub Action

- libs/create-badgen-handler.ts
- libs/measurement-protocol.ts
- package-lock.json
- package.json
Need to find out why the custom measurement-protocol doesn't work 😕
> chore: rollback to universal-analytics

- api/npm.ts
prefer official npm api as much as possible
resolve #292
> chore: use npm api for "latest" tag

- api/github.ts
Implements #357 
Division by 0 is handled and follows GitHub by treating no issues as 0%. Percentages are floored to the nearest integer (e.g 94%)
> feat(github): add milestone percentages

- api/github.ts
- components/home-intro.tsx
contributers -> contributors
Added a full stop.
> docs: fixed typos

- .github/workflows/deploy.yml
Auto confirm deployment questions.
> fix: now deploy command after v17

- api/cocoapods.ts
- libs/badge-list.ts
> Cocoapods support

- .github/workflows/upstream.yml
- test/upstreams.js
Added a cron job monitoring upstream api availability / correctness.
Per discussion in https://github.com/badgen/badgen.net/issues/373#issuecomment-625914798
> test: schedule upstream api tests

- api/opam.ts
These are just _cosmetic_ changes to simplify the scraping part of opam service.
> Refactor opam web scraping

- api/travis.ts
Leverage optional chaining to simplify code.
> Refactor travis

- api/tidelift.ts
Teaching Tidelift badge some manners. :wink:
> Update Tidelift badge

- api/lgtm.ts
This closes #356 
@nekokatt Are you ok with using your work as badge example?
> Support other providers for LGTM badge

- api/snyk.ts
Changing Synk examples per @tunnckoCore's request https://github.com/badgen/badgen.net/pull/394#issuecomment-633729983
> Update snyk examples

- api/github.ts
> fix: use includes and toLowerCase in status endpoint

- README.md
- package-lock.json
- package.json
- ZEIT => Vercel
- Bigger logo
> Update sponsors logo

- api/packagephobia.ts
> packagephobia.now.sh => packagephobia.com

- api/jenkins.ts
- libs/badge-list.ts
- package-lock.json
- package.json
Added a new badge endpoint for Jenkins jobs.
> feat: Added badge endpoint for Jenkins jobs

- api/jenkins.ts
Running lint - `npm run lint` fails with the below output.
```
/badgen.net/api/jenkins.ts
1:30   error  Extra semicolon  semi
2:78   error  Extra semicolon  semi
3:49   error  Extra semicolon  semi
20:3    error  Extra semicolon  semi
38:3    error  Extra semicolon  semi
41:62   error  Extra semicolon  semi
42:2    error  Extra semicolon  semi
45:62   error  Extra semicolon  semi
46:2    error  Extra semicolon  semi
48:60   error  Extra semicolon  semi
49:2    error  Extra semicolon  semi
52:107  error  Extra semicolon  semi
53:41   error  Extra semicolon  semi
57:104  error  Extra semicolon  semi
58:41   error  Extra semicolon  semi
62:61   error  Extra semicolon  semi
67:4    error  Extra semicolon  semi
71:58   error  Extra semicolon  semi
73:52   error  Extra semicolon  semi
74:5 …
```
> style: resolve eslint issues

- .github/workflows/nodejs.yml
This checks for lint & build errors on PR's
> ci: add lint and build workflow on pr

- .github/workflows/deploy.yml
Tested in https://github.com/badgen/badgen.net/runs/1006197731
> fix: now deploy command

- api/docker.ts
This PR facilitates generating architecture variant size badges such as `arm/v6` VS `arm/v7` VS `arm64/v8`. 
This can be tested using the multi-architecture [lucashalbert/curl:latest](https://hub.docker.com/r/lucashalbert/curl)  dockerhub image like so:
* [https://badgen.net/docker/size/lucashalbert/curl/latest/arm/v6](https://badgen.net/docker/size/lucashalbert/curl/latest/arm/v6).
* [https://badgen.net/docker/size/lucashalbert/curl/latest/arm/v7](https://badgen.net/docker/size/lucashalbert/curl/latest/arm/v7).
* [https://badgen.net/docker/size/lucashalbert/curl/latest/arm64/v8](https://badgen.net/docker/size/lucashalbert/curl/latest/arm64/v8).
> feat(docker): add image architecture variant handler

- api/coveralls.ts
> Fix Coveralls badge 

- package-lock.json
- package.json
- fix: enable scaling of "bare" badges as well badgen/badgen#66
> chore: bump badgen to 3.2.2

- .github/workflows/nodejs.yml
Per comment https://github.com/badgen/badgen.net/pull/453#issuecomment-743983653 @wopian
> ci: enable lint on pr from forks

- api/packagist.ts
> fix(packagist): version selection with channel (#448)

- api/travis.ts
Support new default git branch naming convenention.
> Fix Travis badges

- api/opam.ts
Swapping cheerio powered SVG parsing with regex approach due to performance reasons.
> Refactor OPAM badge

- api/snyk.ts
This PR brings the following changes to the implementation of the Snyk badge:
- swapping `cheerio` powered SVG parsing with regex approach
- fixing an issue with default branch name differing from old convetion
> Refactor Snyk badge

- api/pub.ts
Swapping `cheerio` powered html parsing with regex approach.
> Refactor Dart pub badge

- api/pub.ts
> Fix Dart pub scraping

- api/codacy.ts
Refactor & support new default git branch naming convention.
> Fix Codacy badges

- api/cran.ts
Correct version range formatting.
> Fix R version badge

- api/pub.ts
Use pub API for retrieving likes, points & popularity scores.
---
> Add Dart pub points & popularity badges

- api/azure-pipelines.ts
Through refactor of Azure DevOps REST API client with strict URL param validation, non-hard coded default branch and easier build test results fetching using `test/ResultSummaryByBuild` endpoint. :surfer: 
Plus, the Azure badge is now being _parsed_ using regexes instead of `cheerio`.
---
> Fix Azure Pipeline badges

- api/codacy.ts
- api/coveralls.ts
- api/travis.ts
`append` is meant to be used for setting array params.
> Use `URLSearchParams#set` instead of `URLSearchParams#append`

- api/badgesize.ts
- api/david.ts
- api/https.ts
- api/maven.ts
- api/snyk.ts
- api/travis.ts
This is really a bunch of (non-breaking) style tweaks aimed at:
- improving naming consistency
- standardizing dealing with external URL path params
- updating docs to advertise external URL shorthand (with assumed `https:`)
> Style tweaks

- api/azure-pipelines.ts
> Tweak Azure Pipelines badge

- api/badgesize.ts
> Fix badgesize badge

- package-lock.json
- package.json
It can be safely removed since all handlers migrated away from using it. :tada:
> Remove `cheerio`

- api/circleci.ts
Use `encodeURIComponent` instead of `qs.escape`.
Speed up build info retrieval by using `shallow` query param.
> Tweak CircleCI badge

- api/reddit.ts
- libs/badge-list.ts
This adds new handler/s powered by [Reddit API](https://www.reddit.com/dev/api):
```
/reddit/:topic<karma|comment-karma|post-karma>/u/:user
/reddit/subscribers/r/:subreddit
```
---
Proposed here: https://github.com/badgen/badgen.net/issues/219#issuecomment-454200334
> Add Reddit service

- api/pub.ts
> dart-platform and flutter-platform migrate on api

- package-lock.json
- package.json
> chore: bump badgen-icons to 0.21.0

- package-lock.json
- package.json
As defined by the `lockfileVersion` in `package-lock.json`
> Set desired npm version to 7

- api/opam.ts
opam doesn't provide download statistics any more.
> Remove /opam/dm

- api/docker.ts
> fix(docker): support OCI image spec

- libs/badge-list.ts
- next.config.js
- pages/api/apm.ts
- vercel.json
> feat: migrate /apm badges

- libs/badge-list.ts
- next.config.js
- pages/api/ppm.ts
> feat: add ppm support

- libs/badge-list.ts
- libs/badge-list2.ts
- next.config.js
- pages/api/codeclimate.ts
- vercel.json
> feat: migrate /codeclimate

- libs/badge-list.ts
- libs/badge-list2.ts
- next.config.js
- pages/api/codecov.ts
- vercel.json
> feat: migrate /codecov

- api-/pub.ts
- libs/badge-list.ts
- libs/badge-list2.ts
- next.config.js
- pages/api/pub.ts
- vercel.json
> feat: migrate /pub, fix license parsing #557

- api-legacy/liberapay.ts
- api-legacy/opencollective.ts
- package-lock.json
- pages/api/chrome-web-store.ts
> chore: bump dependencies

- libs/got.ts
Follows update in https://github.com/styfle/packagephobia/pull/1051
> feat: add user agent header to outgoing requests

- package-lock.json
- package.json
Support new Chorme extension version parsing. https://github.com/awesome-webextension/webextension-store-meta/pull/9
> fix(chrome-web-store): update extension version parsing

- vercel.json
https://flat.badgen.net/liberapay
Followup: #611
> Fix liberapay flat badges

- pages/api/jsdelivr.ts
- vercel.json
> Fix jsDelivr flat icon

- README.md
I added missing env vars to the Readme
> Add env vars to Readme
